name: Example 1 testing github action 

on: push

jobs:
    job_1:
     runs-on: ubuntu-latest
     steps:
         - name: Hello Greetings!
           run: echo "Hello welcome to the first github action example"

         - name: checkout the repo files
           uses: actions/checkout@v4 

         - name: Welcome Message
           run: |
            echo "Hello welcome to the first github action example"
            ls -ltra
            cat file.txt

         - name: install cowsay
           run: sudo apt-get install cowsay -y
            
         - name: Generate ASCII for fun
           if: success()
           run: |
            cowsay -f elephant "I am a big elephant" >> cowsay_elephant.txt
            cowsay -f cow "I am not elephant" >> cowsay_elephant.txt

         - name: view dragon.txt
           if: success()
           run: cat -n cowsay_elephant.txt




        #  - name: list files and dirctory
        #    run: ls -ltr

        #  - name: read file 
        #    run: cat file.txt
         