name: Matrix with Docker

on:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        image: [hello-world, alpine]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Docker Info
        run: docker info

      - name: Run Hello World
        run: docker run ${{ matrix.image}}
