name: Matrix with Docker

on:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, alpine]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Docker Info
        run: docker info

      - name: Run Hello World
        if: matrix.image == 'hello-world'
        run: docker run --rm hello-world

      - name: Run Alpine
        if: matrix.image == 'alpine'
        run: docker run --rm alpine echo "Hello from Alpine"
