name: Matrix_with_docker

on: 
    push:

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu_latest, windows-latesr]       
                images: [hello-world, alpine] 
        runs-on: ${{ matrix.os }}
        steps:
            - name: check docker info
              run: docker info
              
            - name: run docker ${{ matrix.images }}
              run: docker run ${{ matrix.images }}  
