name: Monitor

on:
  # workflow_run:
  #   workflows:
  #     - "Example 1 testing github action"
  #   types:
  #     - completed
  # schedule:
  #   - cron: '*/1 * * * *'
  workflow_dispatch:


jobs:
    job_1:
     runs-on: ubuntu-latest
     steps:
        # - name: Find monitoring script
        #   run: |
        #    sudo file_name=$(find / -name "system_monitoring.sh" -type f)
        #    sudo echo "SCRIPT_PATH=$file_name" >> $GITHUB_ENV

        # - name: Execute monitoring script
        #   run: |
        #    echo "Script path: $SCRIPT_PATH"
        #    bash "$SCRIPT_PATH"
        - name: checkout the repo files
          uses: actions/checkout@v4 

        - name: Run the monitoring script
          run: sh system_monitoring.sh

        - name: check report output
          if: success()
          run: cat /tmp/system_monitoring_report.txt

