name: Monitor

on:
  workflow_run:
    workflows:
      - "Example 1 testing github action"
    types:
      - completed

jobs:
    job_1:
     runs-on: ubuntu-latest
     steps:
        - name: Execute monitoring script
          run: ./.github/workflows/system_monitoring.sh

