# Notes: Jobs run parallely when we have no defined the order and conditions
name: multiple job 

on: push

jobs:
    Build_job_file_preparation:
        runs-on: ubuntu-latest
        steps:
            - name: Generated Dragon.txt
              run: |
                sudo apt-get install cowsay -y 
                /usr/games/cowsay -f dragon "Build base" >> build.txt
                 file_path=$(find . -type f -name build.txt)
                 echo "$file_path"

            # - name: Sleep time
            #   run: sleep 30

            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: ./build.txt 
                  retention-days: 30   
    
    Testing_content_of_the_file:
        needs: Build_job_file_preparation
        runs-on: ubuntu-latest
        steps:
            # - name: check build.txt is not empty
            #   run: |
            #     file="build.txt"
            #     if [ ! -s "$file" ]; then 
            #       echo "file is empty"
            #     else
            #       echo "$file has data"
            #     fi
            - name: 'Upload Artifact'
              uses: actions/download-artifact@v4
              with:
                  name: my-artifact

            - name: check grep 
              run: grep -i "build" build.txt

            - name: Sleep time
              run: sleep 10    
                
    view_content:
        needs: [Build_job_file_preparation,Testing_content_of_the_file]
        runs-on: ubuntu-latest  
        steps:
            - name: 'Upload Artifact'
              uses: actions/download-artifact@v4
              with:
                  name: my-artifact

            - name: content of build.txt
              run: |
                echo "Content-data"
                cat build.txt




